# Generated by Django 5.2.6 on 2025-09-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at']},
        ),
    ]
